### ISSUE TITLE
Update PyPy

### ISSUE THREAD

**Issue by LizardM4** [beardypig/pymp4#1]
Hello, I noticed that the PyPy version of pymp4 is missing the last two commits. Would it be possible to issue a new release?

The two commits contain many default values that are really handy, `UNITY_MATRIX` and especially the structure for the `avc1` atom, which I think is really essential for MP4.

**Comment by beardypig** [comment]
A new release (1.1.0) has been released on PyPi. Does this cover that for you?

**Comment by LizardM4** [comment]
Yes, that's perfect. Many thanks!
