### ISSUE TITLE
Codecov deactivated?

### ISSUE THREAD

**Issue by rlaphoenix** [beardypig/pymp4#28]
While master still has one failing test (which I have not found out why the seemingly exact same two objects are failing assertion) the Construct 2.10 upgrade is now from all the pull requests finally fully passing all CI workflow steps including tests and coverage. However, the upload the codecov is failing because you seemingly deactivated your configuration with Codecov on the Codecov dashboard?

```
[2023-04-17T20:27:27.901Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 400 - [ErrorDetail(string='This repository has been deactivated. To resume uploading to it, please activate the repository in the codecov UI: https://app.codecov.io/github/beardypig/pymp4/settings', code='invalid')]
```

Is it possible to re-activate it? Or will we go ahead and just remove Codecov (though I feel like it should stay).

By the way. I appreciate you giving me contributor access, but it seems like your hands are full with regard to the upkeep of this project. You don't seem to have the time or need to work on the project and I am wondering if you're willing to let someone else continue maintaining the project? I am willing to take it fully off your hands by transferring the entire project to me. I will try to maintain it as much as I can, as pymp4 is currently used by one of my main bigger projects as well as some of my others. So I have a reason or a push to ensure this project thrives. If not, that is understandable and I will still continue contributing where possible.

**Comment by beardypig** [comment]
I tried to re-activate it, but it doesn't look like it worked exactly as expected.

**Comment by beardypig** [comment]
OK - I fixed it. I guess I needed my coffee.
