### ISSUE TITLE
more pull requests?

### ISSUE THREAD

**Issue by finnhughes** [beardypig/pymp4#7]
Not really an issue but I wasn't sure how to reach out. I noticed that you recently merged a couple of my pull requests so wondered if I should submit some more? I haven't touched my fork in a while but I had more changes I never worked into pull requests
e.g. basic udta parsing:
https://github.com/finnhughes/pymp4/commit/67f5a697821ef6aac7d673e25b88396b9c84ef99
or enabling support for extended size fields in mdat:
https://github.com/finnhughes/pymp4/commit/7f846a752a20d92e0798a21706cbe9868f2f6508

**Comment by beardypig** [comment]
Sure, I’ll accept PRs :) You make nice PRs with tests... make sure to rebase, there were some travis/test fixes I had to do to make it build.

**Comment by beardypig** [comment]
FYI, I’m always available by electronic mail: beardypig <email symbol, ya know> protonmail <dot> com :)
