### ISSUE TITLE
unable to get all box data

### ISSUE THREAD

**Issue by jiujitsu** [beardypig/pymp4#8]
Hello, I apologize in advance if this is user error and not a bug. The mp4 file in question is: [here](https://pe-ak-vp07a-9c9media.akamaized.net/playlist/3285222/68817164/dash/20130001/070ff3322a0184bb/index/a844f489/none/none/stream/h264/v2/3500000/init.mp4)

My code:
```
boxes = Box.parse_stream(open('init.mp4', 'rb'))
[box for box in boxes]
```
Gives output:
`['offset', 'type', 'major_brand', 'minor_version', 'compatible_brands', 'end']`

However when I use [mp4dump](https://www.bento4.com/documentation/mp4dump/) (not pymp4 cli) I see the full box data. Am I doing something wrong?

**Comment by beardypig** [comment]
Did you solve this?

**Comment by Random-Code-Guy** [comment]
> Did you solve this?

i am trying to get the box and box type using pymp4 using the following 


```
    boxes = Box.parse_stream(io.BytesIO(data))
    for box in boxes:
        if box.type == b"senc":
            print("found")
```

but all i get is string dosent have type error and i dont see a lot of documentation on this project and how it can be used apart from a few examples
